services:
  # Prod environment is supposed to use a distant database, so we do not need to run a mariadb container

  ecommerce-symfony-s:
    container_name: "ecommerce-symfony-c"
    build:
      context: ../
      dockerfile: ".docker/symfony/Dockerfile.prod"
    env_file:
      - "symfony/.env.prod"
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - ecommerce-network

  ecommerce-nginx-s:
    container_name: "ecommerce-nginx-c"
    build:
      context: ../
      dockerfile: ".docker/nginx/Dockerfile.prod"
    env_file:
      - "nginx/.env.prod"
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - ecommerce-network
    depends_on:
      - ecommerce-symfony-s

networks:
  ecommerce-network:
    driver: bridge